name: Publish API docs

# on:
#   push:
#     branches:
#     - main
#   pull_request:
on:  [push, pull_request]

env:
  MODO_VERSION: 16b8b5d5dcd0dc4953ad1f809751bf234e47a86c # 0.11.1
  HUGO_VERSION: mojo-lexer # 0.140.2

jobs:

  publish:
    name: Publish API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ExtraMojo
        uses: actions/checkout@v3
      - name: Install magic CLI
        run: |
          curl -ssL https://magic.modular.com | bash
          source /home/runner/.bash_profile
        
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.x'

      # # Install Modo from commit hash
      # - name: Clone Modo
      #   run: |
      #     git clone https://github.com/mlange-42/modo.git
      #     cd modo
      #     git checkout ${{env.MODO_VERSION}}
      # - name: Build Modo
      #   run: |
      #     cd modo
      #     go get .
      #     go build .
      
      # Download Modo release
      - name: Download Modo
        run: |
          mkdir modo/
          curl -sSL https://github.com/mlange-42/modo/releases/download/v${{env.MODO_VERSION}}/modo-v${{env.MODO_VERSION}}-linux-amd64.tar.gz | tar -xz -C modo/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{env.HUGO_VERSION}}'
          extended: true

      # - name: Clone Hugo
      #   run: |
      #     git clone https://github.com/mlange-42/hugo.git
      #     cd hugo
      #     git checkout ${{env.HUGO_VERSION}}
      # - name: Install Hugo
      #   run: |
      #     cd hugo
      #     go install .
        
      - name: Run Modo # Includes 'mojo doc' and 'mojo test'
        run: |
          source /home/runner/.bash_profile
          magic install --locked
          ./modo/modo build
      
      - name: Run Hugo
        run: |
          hugo -s docs/site

      - name: Archive Doc-tests
        uses: actions/upload-artifact@v4
        with:
          name: doctest
          path: docs/test
      - name: Archive Markdown artifacts
        uses: actions/upload-artifact@v4
        with:
          name: markdown
          path: docs/site/content
      - name: Archive HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: docs/site/public

      - name: Deploy to GitHub Pages
          # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/site/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}